### ISSUE TITLE
Undefined property: WebUser::$username

### ISSUE THREAD

**Issue by glendemon** [glendemon/yboard#10]
yboard-master/index.php?cat_id=1

Error 500
 Undefined property: WebUser::$username

**Comment by vencendor** [comment]
покажи с кукой YII_DEBUG

**Comment by glendemon** [comment]
Добавил в index.php, но во внешнем виде ничего не поменялось(

**Comment by vencendor** [comment]
в верхнем правом углу иконка от расширения Yii_debug должно появится 
проверь путь куки, дату и значение = yes
