### ISSUE TITLE
Издевательство над фреймворком и MVC в целом

### ISSUE THREAD

**Issue by urichalex** [glendemon/yboard#11]
Прежде, чем создавать проект на фреймворке, изучили бы хотя-бы сам MVC..
В контроллерах вывод, в моделях непойми что. Половина аттрибутов мультиязычна, другая половина либо просто строкой, либо t() что за t()?
Зачем Вы закоммитили nbproject??? Разве так сложно добавить его в исключения?
А про использование запросов и элементарные ошибки я лучше вообще промолчу...
Что это такое?
$this->categories = $command = Yii::app()->db->createCommand('SELECT * FROM category')
                                ->queryAll();
Что за двойное присваивание, при чем $command вообще нигде потом не используется
Вы же используете MVC, создали модель для этой таблицы, а используете билдер. И этих  билдеров не один и не два. Может Вам нужно было просто взять готовый конструктор запросов, и написать без использования фреймворка?
Мое мнение, вот из-за таких проектов общество и не любит РНР и его программистов...

**Comment by urichalex** [comment]
global $CONFIG; о_О
Yii framework гордится тем, что неиспользует глобальных переменных. Нет, надо всё изуродовать...

**Comment by urichalex** [comment]
Мля, капец!!!
$db_con=@mysqli_connect($server,$username,$password) or $db_error = mysqli_error();
                        @mysqli_select_db($db_con,$db_name) or $db_error = mysqli_error($db_con);

Я дальше не читаю!!!

**Comment by vencendor** [comment]
Спасибо за замечания, учтем. 

Если у Вас есть более подходящие решения с радостью рассмотрим ваши комиты.

**Comment by urichalex** [comment]
Нет уж. Примите к сведению мои замечания и исправьте сами ;-)

**Comment by urichalex** [comment]
Завтра на ра работе загружу в иде

**Comment by CawaKharkov** [comment]
Вот еще "неплохой" кусочек 
https://github.com/glendemon/yboard/blob/master/protected/controllers/AdvertsController.php#L77

**Comment by vencendor** [comment]
Как бы вы предложили его переделать ?

**Comment by urichalex** [comment]
>> Как бы вы предложили его переделать ?
Вывод должен быть ТОЛЬКО в представлении. Это MVC - Model - VIEW - Controller. И каждая выполняет свою роль. Модель - логика. Контроллер - подготовка к выводу, представление - вывод. И только так. Исключения составляют только AJAX запросы

**Comment by urichalex** [comment]
>> Вот еще "неплохой" кусочек:
Не заметил =)))

**Comment by vencendor** [comment]
Теоретический подход понятен. Как на практике вы бы реализовали этот функционал?

**Comment by urichalex** [comment]
>>Теоретический подход понятен. Как на практике вы бы реализовали этот функционал?

Если я правильно понял, это действие для AJAX. Если да, то так

```php
$fields = [];
foreach ($fields as $f_iden => $fv) {
    $fields[] = [
        'id' => $f_iden,
        'label' => $fv->name
    ];
}
$json = CJSON::encode($fields);
Yii::app()->end($json);
```

**Comment by KirillKrasyuk** [comment]
А чем плох метод формирования html при ajax запросах? Например вывести все это в отдельный контроллер, который будет возвращать такие штуки.
Я понимаю что MVC и все такое, но если надо сформировать список свойств в фрму на основе категория+свойства, то лучше это делать в JS на клиенте?
Получается то же самый код, только в JS.

**Comment by CawaKharkov** [comment]
@KirillKrasyuk умные люди давно придумали js шаблонизаторы, такие как handlebars

**Comment by vencendor** [comment]
Если у вас есть идея как тот или иной блок реализовать лучше - смелей в код, мы открыты для конструктивных предложений.

Мы готовы принимать критику и реализовывать более качественный продукт. Однако цель проекта - доступность! 
Минимум дополнительных технологий которыми не являются лидирующими или стандартами. 
Минимум дополнительных файлов для возможности создания шаблонов проекта.
Максимум функционала, именно поэтому в некоторым моментах могут быть "не кошерные" методы решения задачи, однако критичным является правильная работа а не чтобы код всем понравился. Кому код не нравится может его улучшить, однако таких пока не наблюдаются, одни критики, без капли реальной пользы.

**Comment by urichalex** [comment]
LДело не в том, нравится код или нет. Дело в том, что, раз уж Вы взялись использовать фреймворк, основанный на паттерне MVC, будьте добры придерживаться этого паттерна. Иначе же используйте процедурный стиль и пишите в стиле а-ля прошлый век.
Помогать Вам реализовывать... Ладно бы если бы там пару тройку мест, дак там все в идеале переписать нужно
