### ISSUE TITLE
 Undefined variable: id

### ISSUE THREAD

**Issue by woffpost** [glendemon/yboard#21]
Привет, столкнулся с такой проблемой, пока не нашел решение:

Notice: Undefined variable: id in /var/www/yboard/protected/modules/cms/components/CmsHandler.php on line 12

причем в http://yboard.conf/site/install/ могу зайти, прохожу первый шаг установки, нажимаю "Сохранить" и получаю нотайс, описанный выше

**Comment by vencendor** [comment]
Отключите нотисы. уровень вывода ошибок поставьте warning

**Comment by woffpost** [comment]
Как оперативно! Спасибо, дело в том, что я их и вывел для того чтобы понять в чем проблема, при отключении вывода ошибок (так было в архиве, который скачал отсюда), просто белая страница выводится. После поисков в гугле, нашел несколько ответов где у ребят та же ошибка, в компоненте cms... вот сижу мучаюсь...

**Comment by vencendor** [comment]
пробуйте ставить куку YII_DEBUG там выводится отладочная информация. С модулем cms вроде не было проблем. если точно покажете ошибку исправлю. 

Баг репорты приветствуются - но нужна отладочная информация

**Comment by woffpost** [comment]
Понял, после включения YII_DEBUG, в application.log записалось

2015/04/25 19:32:00 [error] [php] file_put_contents(/var/www/yboard/protected/config/main.php): failed to open stream: Permission denied (/var/www/yboard/protected/controllers/SiteController.php:169)
Stack trace:
#0 /var/www/yboard/framework/web/CController.php(308): CInlineAction->runWithParams()
#1 /var/www/yboard/framework/web/filters/CFilterChain.php(133): SiteController->runAction()
#2 /var/www/yboard/framework/web/filters/CFilter.php(40): CFilterChain->run()
#3 /var/www/yboard/framework/web/CController.php(1145): CAccessControlFilter->filter()
#4 /var/www/yboard/framework/web/filters/CInlineFilter.php(58): SiteController->filterAccessControl()
#5 /var/www/yboard/framework/web/filters/CFilterChain.php(130): CInlineFilter->filter()
#6 /var/www/yboard/framework/web/CController.php(291): CFilterChain->run()
#7 /var/www/yboard/framework/web/CController.php(265): SiteController->runActionWithFilters()
#8 /var/www/yboard/framework/web/CWebApplication.php(282): SiteController->run()
#9 /var/www/yboard/framework/web/CWebApplication.php(141): CWebApplication->runController()
#10 /var/www/yboard/framework/base/CApplication.php(184): CWebApplication->processRequest()
#11 /var/www/yboard/index.php(23): CWebApplication->run()
REQUEST_URI=/site/install

Права на проект поставил 755,
на папки 
/protected/runtime   777
и 
/assets 777

**Comment by vencendor** [comment]
Да, с правами нужно уточнить, если не сложно напиши список папок которым изменил права на запись

**Comment by woffpost** [comment]
Собственно на весь проект дал 755, а потом protected/runtime установил 777 и assets 777, если это не гуд, снесу проект и установлю заново, благо пока это все дело локально подымаю)
а если именно список всех папок нужен - то вот он

**Comment by deliverys** [comment]
Привет!

https://github.com/glendemon/yboard/commit/fbab6c5565f30a9297a80dd61dad47d540b877a8


Суббота, 25 апреля 2015, 9:13 -07:00 от Maxim Uglov <notifications@github.com>:

**Comment by deliverys** [comment]
Привет с праздником!
Еще я так и не поборол проблему, при регистрации аккаунта заполняются все поля, создается аккаунт, но под логином этим не зайти, пишет о том что аккаунт не активирован обратитесь к админу, в админке я не увидел как активировать пользователей, письмо о регистрации не приходит юзеру с активацией..подскажи плиз


Суббота, 25 апреля 2015, 9:13 -07:00 от Maxim Uglov <notifications@github.com>:
