### ISSUE TITLE
проект умер?

### ISSUE THREAD

**Issue by Kamik** [glendemon/yboard#25]

**Comment by vencendor** [comment]
нет. скоро будет обновление

**Comment by vencendor** [comment]
какие задачи вам интересны?

**Comment by luk911** [comment]
а демо где нибудь есть ?

**Comment by Kamik** [comment]
пока просто присматриваю, какой скрипт использовать для проекта. Платные не очень привлекают закрытым кодом. На неделе поставлю ваш, возможно включусь в разработку.

**Comment by kolexndr** [comment]
Kamik, я абсолютно в такой же ситуации как и вы. Никак не определюсь. Для рассмотрения взял  ещё вот этот: https://github.com/hamjoint/mustard
Не знаю насколько корректно здесь указывать ссылку на конкурирующий проект.

**Comment by vencendor** [comment]
Последние обновления будут выкладываться в ветке https://github.com/vencendor/yboard 

Просьба сообщать о найденных багах
