### ISSUE TITLE
доска умерла?

### ISSUE THREAD

**Issue by nicdnepr** [glendemon/yboard#27]
когда будут обновления?

**Comment by Siteograf** [comment]
Переписываете на другом фреймворке?

**Comment by glendemon** [comment]
Добрый день. Возможно будет версия 2.0 на yii2, но не факт.

**Comment by Siteograf** [comment]
В сторону Phalcon смотрели?

**Comment by glendemon** [comment]
Только на уровне обзоров

**Comment by vencendor** [comment]
Последние обновления будут появляться в ветке https://github.com/vencendor/yboard
Переписывать на другой движок нет смысла
